FROM amazoncorretto:17-alpine3.16-full

RUN apk update && apk upgrade
RUN apk add nodejs npm

WORKDIR /app

COPY . .

RUN ./mvnw clean package -Pproduction

EXPOSE 8080
RUN java -jar target/projecttryhilla-1.0-SNAPSHOT.jar